# Example docker-compose configuration for the bot service
# Build the image from the local Dockerfile and pass through
# some of the environment variables declared in the Dockerfile.
# Code also doesn't need any mounted volumes, everything works dynamically through volumes
#
# Usage:
#   docker-compose up --build to build it manually
#   docker-compose up to just use it as it is
#
services:
  wocabee:
    build:
      context: .
      dockerfile: Dockerfile
      network: host
    image: ghcr.io/toomcis/wocafuckoff:latest  # Image path
    container_name: wocafuckoff
    restart: "no"
    environment:
      - TARGET_URL=${TARGET_URL} # Targeting URL for bot to interact, dont change unless you know what you are doing
      - WORDLIST_FILE=${WORDLIST_FILE} # Path to wordlist file, doesn't need mounting, optional
      - PICTURE_FILE=${PICTURE_FILE} # Path to picture file, doesn't need mounting, optional
      - PLACEHOLDER_WORDS=${PLACEHOLDER_WORDS} # Comma separated list of placeholder words to ignore, optional
      - CLASS_INDEX=${CLASS_INDEX} # Class index to target, default is 0 for first class, optional
      - PACKAGE_INDEX=${PACKAGE_INDEX} # Package index to target, default is 0 for first package, optional
      - USERNAME=${USERNAME} # Username for login into Wocabee
      - PASSWORD=${PASSWORD} # Password for login into Wocabee
      - DOUBLE_POINTS=${DOUBLE_POINTS} # Set to true to enable double points mode, default is false for normal more, optional
      - ADDON_POINTS=${ADDON_POINTS} # Number of addon points to use, default is 5000
      - MILESTONE_REMINDER=${MILESTONE_REMINDER} # Number of points to trigger milestone reminder, default is 1000, optional
      - NTFY_SERVER=${NTFY_SERVER} # NTFY server URL for notifications, optional
      - NTFY_TOPIC=${NTFY_TOPIC} # NTFY topic for notifications, optional
      - NTFY_TOKEN=${NTFY_TOKEN} # NTFY token for authentication, optional
    tty: true
    stdin_open: true
    network_mode: "host"
