#!/bin/bash
set -e

echo -e "nameserver 8.8.8.8\nnameserver 1.1.1.1" > /etc/resolv.conf || true

CONFIG_FILE="/bot/config.toml"

# --- Pull latest wordlist and picturelist from the repo ---
if [ -d "/bot/data" ]; then
    echo "Volume /bot/data detected — using local JSON files instead of git pull"
    [ -f "/bot/data/wordlist.json" ]    && cp /bot/data/wordlist.json    /bot/wordlist.json
    [ -f "/bot/data/picturelist.json" ] && cp /bot/data/picturelist.json /bot/picturelist.json
else
    echo "Pulling latest wordlist and picturelist from git..."
    cd /bot
    git fetch origin 2>/dev/null || true
    git checkout origin/main -- wordlist.json picturelist.json 2>/dev/null \
        || git checkout origin/master -- wordlist.json picturelist.json 2>/dev/null \
        || echo "Warning: could not pull JSON files from git"
fi

# --- Normalize booleans: true/True/TRUE/1/yes -> true, everything else -> false ---
normalize_bool() {
    case "$(echo "$1" | tr '[:upper:]' '[:lower:]')" in
        true|1|yes) echo "true" ;;
        *) echo "false" ;;
    esac
}

# --- Strip surrounding quotes/backticks from a value ---
strip_quotes() {
    echo "$1" | sed "s/^['\"\`]*//;s/['\"\`]*$//"
}

# --- Normalize all variables ---
DOUBLE_POINTS=$(normalize_bool "$(strip_quotes "${DOUBLE_POINTS:-false}")")
CLASS_INDEX=$(strip_quotes "${CLASS_INDEX:-0}")
PACKAGE_INDEX=$(strip_quotes "${PACKAGE_INDEX:-0}")
ADDON_POINTS=$(strip_quotes "${ADDON_POINTS:-5000}")
MILESTONE_REMINDER=$(strip_quotes "${MILESTONE_REMINDER:-1000}")
TARGET_URL=$(strip_quotes "${TARGET_URL:-https://wocabee.app/app}")
USERNAME=$(strip_quotes "${USERNAME:-}")
PASSWORD=$(strip_quotes "${PASSWORD:-}")
NTFY_SERVER=$(strip_quotes "${NTFY_SERVER:-}")
NTFY_TOPIC=$(strip_quotes "${NTFY_TOPIC:-}")
NTFY_TOKEN=$(strip_quotes "${NTFY_TOKEN:-}")
WORDLIST_FILE=$(strip_quotes "${WORDLIST_FILE:-wordlist.json}")
PICTURE_FILE=$(strip_quotes "${PICTURE_FILE:-picturelist.json}")

# --- Prepare placeholder_words safely ---
if [ -z "$PLACEHOLDER_WORDS" ]; then
    PLACEHOLDER_WORDS='["translate","check"]'
else
    PLACEHOLDER_WORDS=$(strip_quotes "$PLACEHOLDER_WORDS")
    PLACEHOLDER_WORDS=$(echo "$PLACEHOLDER_WORDS" | tr ',' '\n' \
        | sed 's/^\s*//;s/\s*$//' \
        | awk '{printf "\"%s\",",$0}' \
        | sed 's/,$//')
    PLACEHOLDER_WORDS="[$PLACEHOLDER_WORDS]"
fi

# --- Create or update config.toml ---
cat > "$CONFIG_FILE" << EOF
# Auto-generated by entrypoint
urlbase="${TARGET_URL}"
debug_port="http://localhost:9222"
wordlist_file="${WORDLIST_FILE}"
picture_file="${PICTURE_FILE}"
placeholder_words=${PLACEHOLDER_WORDS}
class_index=${CLASS_INDEX}
package_index=${PACKAGE_INDEX}
addon_points=${ADDON_POINTS}
milestone_reminder=${MILESTONE_REMINDER}
double_points=${DOUBLE_POINTS}
headless=true
username="${USERNAME}"
password="${PASSWORD}"
ntfy_server="${NTFY_SERVER}"
ntfy_topic="${NTFY_TOPIC}"
ntfy_token="${NTFY_TOKEN}"
EOF

echo "Generated config.toml:"
cat "$CONFIG_FILE"
echo "---------------------"

# --- Start the bot ---
/opt/venv/bin/python /bot/startup.py
BOT_EXIT=$?

# --- Write back updated JSON files to volume (if mounted) ---
if [ -d "/bot/data" ]; then
    echo "Syncing updated word/picture lists back to /bot/data..."
    [ -f "/bot/wordlist.json" ]    && cp /bot/wordlist.json    /bot/data/wordlist.json
    [ -f "/bot/picturelist.json" ] && cp /bot/picturelist.json /bot/data/picturelist.json
    echo "Sync complete."
fi

exit $BOT_EXIT