#!/bin/bash
set -e

# Helper to strip surrounding quotes
strip_quotes() {
    echo "$1" | sed 's/^"\(.*\)"$/\1/'
}

# --- Base Settings ---
TARGET_URL=$(strip_quotes "${TARGET_URL:-https://wocabee.app/app}")
WORDLIST_FILE=$(strip_quotes "${WORDLIST_FILE:-wordlist.json}")
PICTURE_FILE=$(strip_quotes "${PICTURE_FILE:-picturelist.json}")
USERNAME=$(strip_quotes "${USERNAME:-}")
PASSWORD=$(strip_quotes "${PASSWORD:-}")

CLASS_INDEX=${CLASS_INDEX:-0}
PACKAGE_INDEX=${PACKAGE_INDEX:-0}

ADDON_POINTS=${ADDON_POINTS:-5000}
MILESTONE_REMINDER=${MILESTONE_REMINDER:-1000}

# Ensure DOUBLE_POINTS is lowercase boolean
DOUBLE_POINTS=$(echo "${DOUBLE_POINTS:-false}" | tr '[:upper:]' '[:lower:]')
if [ "$DOUBLE_POINTS" != "true" ]; then
    DOUBLE_POINTS="false"
fi

# --- Placeholder Words as TOML Array ---
if [ -z "$PLACEHOLDER_WORDS" ]; then
    PLACEHOLDER_WORDS='["","translate","check"]'
else
    PLACEHOLDER_WORDS=$(echo "$PLACEHOLDER_WORDS" | tr ',' '\n' \
        | sed 's/^\s*//;s/\s*$//' \
        | awk '{printf "\"%s\",",$0}' \
        | sed 's/,$//')
    PLACEHOLDER_WORDS="[$PLACEHOLDER_WORDS]"
fi

# --- NTFY Settings ---
NTFY_SERVER=$(strip_quotes "${NTFY_SERVER:-}")
NTFY_TOPIC=$(strip_quotes "${NTFY_TOPIC:-}")
NTFY_TOKEN=$(strip_quotes "${NTFY_TOKEN:-}")

# --- Generate config.toml ---
cat > /bot/config.toml << EOF
# Auto-generated by entrypoint

urlbase = "$TARGET_URL"
debug_port = "http://localhost:9222"
wordlist_file = "$WORDLIST_FILE"
picture_file = "$PICTURE_FILE"

placeholder_words = $PLACEHOLDER_WORDS

class_index = $CLASS_INDEX
package_index = $PACKAGE_INDEX

addon_points = $ADDON_POINTS
milestone_reminder = $MILESTONE_REMINDER

double_points = $DOUBLE_POINTS

username = "$USERNAME"
password = "$PASSWORD"

ntfy_server = "$NTFY_SERVER"
ntfy_topic = "$NTFY_TOPIC"
ntfy_token = "$NTFY_TOKEN"
EOF

echo "--- Generated config.toml ---"
cat /bot/config.toml
echo "----------------------------"

# Forward any CMD arguments (starts your bot)
exec "$@"