#!/bin/bash
set -e

CONFIG_FILE="/bot/config.toml"

# --- Prepare placeholder_words safely ---
if [ -z "$PLACEHOLDER_WORDS" ]; then
    PLACEHOLDER_WORDS='["translate","check"]'
else
    # Split comma-separated env var, trim spaces, quote each item
    PLACEHOLDER_WORDS=$(echo "$PLACEHOLDER_WORDS" | tr ',' '\n' \
        | sed 's/^\s*//;s/\s*$//' \
        | awk '{printf "\"%s\",",$0}' \
        | sed 's/,$//')
    PLACEHOLDER_WORDS="[$PLACEHOLDER_WORDS]"
fi

# --- Create or update config.toml ---
cat > "$CONFIG_FILE" << EOF
# Auto-generated by entrypoint
urlbase="${TARGET_URL:-https://wocabee.app/app}"
debug_port="http://localhost:9222"
wordlist_file="${WORDLIST_FILE:-wordlist.json}"
picture_file="${PICTURE_FILE:-picturelist.json}"
placeholder_words=${PLACEHOLDER_WORDS}
class_index=${CLASS_INDEX:-0}
package_index=${PACKAGE_INDEX:-0}
addon_points=${ADDON_POINTS:-5000}
milestone_reminder=${MILESTONE_REMINDER:-1000}
double_points=${DOUBLE_POINTS:-false}
headless=true
username="${USERNAME:-}"
password="${PASSWORD:-}"
ntfy_server="${NTFY_SERVER:-}"
ntfy_topic="${NTFY_TOPIC:-}"
ntfy_token="${NTFY_TOKEN:-}"
EOF

echo "Generated config.toml:"
cat "$CONFIG_FILE"
echo "---------------------"

# --- Start the bot ---
exec /opt/venv/bin/python /bot/startup.py